GovWifi/govwifi-tech-docs

Dockerfile, Makefile, docker-compose.yml, manifest.yml
This introduces docker and a Makefile to build the documentation and the
ability to deploy it.
Depends on CF_USER and CF_PASS environment variables being set.
=> [WIP] Build and deploy the application to CloudFoundry

Dockerfile, Makefile
Also remove debugging information
=> Improve syntax of Makefile

source/documentation/about.md, source/documentation/before_you_start.md, source/documentation/leave.md, source/documentation/phase1.md, source/documentation/phase2.md, source/documentation/phase3.md, source/documentation/phase4.md, source/documentation/phase5.md, source/documentation/phase6.md, source/documentation/requirements.md, source/documentation/troubleshooting.md
Some of these instructions are likely to change, but bring everything
over for now which will make it easier to scan for changes than the google doc.
=> Copy over content in current form

source/before_you_start.html.md.erb, source/index.html.md.erb, source/leave.html.md.erb, source/phase1.html.md.erb, source/phase2.html.md.erb, source/phase3.html.md.erb, source/phase4.html.md.erb, source/phase5.html.md.erb, source/phase6.html.md.erb, source/requirements.html.md.erb, source/troubleshooting.html.md.erb
The navigation heading ordering was random, control this with the weight
configuration
=> Add weight to order navigation

config/tech-docs.yml
=> Enalble collapsible navigation in the sidebar

source/documentation/before_you_start.md, source/documentation/leave.md, source/documentation/phase1.md, source/documentation/phase2.md, source/documentation/phase3.md, source/documentation/phase4.md, source/documentation/phase5.md, source/documentation/requirements.md
H3 tags were creating nested sub menus, change these for bold tags.
Also remove outdated content documenting the email flow, this will not
be required or replaced with instructions about the admin platform.
=> Reduce the nesting of the navigation menu

source/acceptable_usage.html.md.erb, source/documentation/acceptable_usage.md, source/phase6.html.md.erb, source/troubleshooting.html.md.erb
This is very much a first draft.
=> Add advice on policy and removing GovWifi users

config/tech-docs.yml
=> Add tracking ID

Gemfile, config.rb, config/tech-docs.yml
Add script to allow cross domain tracking from the tech docs to admin and product pages.
=> [WIP]: Add Google Analytics Script

source/documentation/set_up.md
This commit fixes the numbering of the surrounding list (was 1, 2, 3, 1, 2, 3)
Old:
New:
=> Correct Markdown nested list 

source/documentation/set_up.md
=> Restructure GovWifi setup text

config/tech-docs.yml
=> Add beta phase tag

source/documentation/orgs_terms_and_conditions.md
Added link to download MoU from admin portal.
=> Link MoU to Admin Portal

source/javascripts/application.js, source/javascripts/google_tag_manager.js
This is a reimplementation.
The container is new so it has a different container ID which is why PR #40 wasn't reverted. 
**Suggestions and feedback would be appreciated.**
=> Reimplement new GTM script

ci/pipelines/deploy.yml
everything must go under 'plan', and we need to load the runner
=> fix the deploy pipeline

source/documentation/orgs_terms_and_conditions.md, source/orgs_terms_and_conditions.html.md.erb
=> Completely remove T&Cs from Docs

ci/pipelines/pr.yml
=> Fix misspelled job

source/assets/govwifi-profile.xml, source/documentation/set_up.md
This was previously lost, as the old repository was removed
=> move our wifi profile to the docs repo

source/manage.html.md.erb
We want to make clear that this content is for administrators in search engine results
=> Update 'manage govwifi' to be more SEO friendly

source/set_up.html.md.erb
We want to make clear that this content is for administrators in search engine results
=> Make 'set up' more SEO friendly

source/documentation/troubleshooting.md
Update Support information on tech docs
Rebuild of https://github.com/alphagov/govwifi-tech-docs/pull/75
=> Vgphb19 patch 6 -  Update Support information on tech docs

source/documentation/introduction.md
We need to provide more context on the intro page of tech docs about what the GovWifi service proposition is
=> Give more info about GovWifi service

source/documentation/requirements.md, source/documentation/set_up.md, source/documentation/troubleshooting.md
These were suggested by Sabrina Harris (thanks!).
=> Make docs more accessible and inclusive

source/documentation/introduction.md, source/documentation/manage.md, source/documentation/requirements.md, source/documentation/set_up.md, source/documentation/troubleshooting.md
Small changes for clarity and consistency. Includes changing references to GovWifi admin and making headings and link text more descriptive.
=> Content changes to support docs

source/documentation/set_up.md
Telling organisations to sign up to status page so they get told about incidents.
=> Add SSID and status page instructions

source/documentation/set_up.md
Add a few sentences encouraging people to add more team members to GovWifi admin. 
So there's someone who can reset their 2FA if they need it.
=> Add content about having multiple admins

source/accessibility.html.md.erb
Update the accessibility statement.
Since the DAC review, updates are required.
Link to Trello card (if applicable): https://trello.com/c/pXrooZzP
=> Update the accessibility statement

source/documentation/manage.md, source/documentation/set_up.md
Just a couple of small style changes that we missed in the latest round of changes.
=> Heading change, remove ts&cs link

source/documentation/set_up.md
The GovWifi team has completed the second rebuild of the Staging environment, and we are happy to reduce RTO to 5 days.
We want to keep our documentation up-to-date.
=> Update to a recovery time objective.

source/documentation/certificate-rotation.md
Update certificate rotation date.
Updating with correct information.
=> Update certificate rotation date

source/documentation/set_up.md
Added information to the technical documentation to assist users on signing up correctly.
End users getting confused and signing up to be admins.
Link to Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=62c2bb48159944bf7687d333&selectedIssue=GW-484
=> add changes to tech documentation to help user sign up

.github/workflows/deploy.yml
Change deploy on PR created to Push to Master
Deployment from a created PR which may be deleted later is not desirable
Link to Trello card (if applicable):
=> Change to deploy on push to Master branch

source/documentation/troubleshooting.md
New edition of troubleshooting guidance including steps for support desks to try with users.
Improve guidance available to support desk staff when they help end users with GovWifi. Reduce first line requests to GovWifi support.
https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-608
=> Revised troubleshooting guidance

config/tech-docs.yml
This feature was added to help Users report issues they find and also how they can contribute.
Describe the change
This feature was added to help Users report issues they find and also how they can contribute.
Describe why the change was necessary
Some users would like to know how to contribute to the Tech-docs website.
Link to Trello card (if applicable): 
https://technologyprogramme.atlassian.net/browse/GW-472
=> Adds Footer with links to Github repo

source/documentation/requirements.md
H2 text tweaked to be more descriptive
RADIUS acronym introduced in full in first instance 
Hyperlink to next section of tech docs added at bottom of page
Improve user experience in tech docs
[GW-686](https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-686)
[GW-686]: https://technologyprogramme.atlassian.net/browse/GW-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Text changes to setup your network tech doc

source/documentation/set_up.md
Link to the preceding section (setup your network) added 
Bolded markdown added to mentions of interface text 
Small text changes
Improve user experience of tech docs
[GW-686](https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-686)
[GW-686]: https://technologyprogramme.atlassian.net/browse/GW-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Text changes to setup GovWifi for your org tech doc

source/documentation/set_up.md
Text change to explain that Port 1813 is closed.
Clear instructions for admins when setting up infrastructure.
GW-156 https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-156
=> Text change to configure your infrastructure section

source/documentation/set_up.md
Indent added to markdown to correct numbering issue (GW-769)
Indent added to markdown to correct numbering issue
Numbered steps were not displaying sequentially. Indenting the paragraph that separates the numbered steps should correct this.
GW-769 https://technologyprogramme.atlassian.net/browse/GW-769
=> Markdown tweak in setup GovWifi for your org

.dependabot/config.yml
Enable dependabot by setting the version to 2 as per documentation
=> Enable Dependabot

source/documentation/set_up.md
Add a guidance note covering time sync on two-factor authentication devices
We had an issue with an organisation and this commit should prevent a reoccurrence
n/a
=> add a guidance note for time sync

source/documentation/certificate-rotation.md
Need to update URLs to Orgs admins can download correct certificate set.
Service certificate is new.
=> Updating URLs to reflect paths for 2024 assets uploaded earlier.

.github/ISSUE_TEMPLATE/report-an-issue-with-govwifi-documentation-.md
=> Update issue templates

package.json
Update shared frontend library
fix security issues with libraries
[GW-2224](https://technologyprogramme.atlassian.net/browse/GW-2224)
=> chore: [GW-2224] update shared frontend lib
