GovWifi/govwifi-tech-docs

Gemfile
Gemfile.lock

On the latest version of this we get an error:
Stack Level Too Deep
It looks like this commit introduced the bug:
https://github.com/alphagov/middleman-search/commit/50d072378c6f92a78ea02fed366ec6453aea8552
Lock down the gem to a version before that.

Lock middleman search gem down to a specific version

---

Dockerfile
Gemfile.lock

There was a problem previously where bundle install failed on Jenkins.
I thought this had to do with the way the docker image is built but
turns out that the git sha in the Gemfile.lock changed to a shorter
version.

Revert Dockerfile syntax

---

config/tech-docs.yml

- Tech docs logo should link back to product page
- Tech docs - Remove Get started, remove support and about add sign in

Change links according to feedback

---

source/documentation/before_you_start.md
source/documentation/leave.md
source/documentation/phase1.md
source/documentation/phase2.md
source/documentation/phase3.md
source/documentation/phase4.md
source/documentation/phase5.md
source/documentation/phase6.md
source/documentation/requirements.md
source/documentation/troubleshooting.md

Email guidance still existed in these docs - admittedly marked by giant deprecation notices - this PR removes them for the sake of clarity.
This PR also points users to our support e-mail address or the new admin platform when they'd otherwise hit a deadend, which was lots of places - looking for an MOU, looking for logs, looking for help in general.
Also correct some list formatting and some confusing blank headings (though some headings are left in, commented, to avoid stepping on toes - happy to remove them instead).

Remove dead-ends and email guidance

---

config/tech-docs.yml
source/stylesheets/screen.css.scss

This top navigation is shared by 3 separate apps, we want it to feel
like you are browsing one app.
All 3 applications should have the same navigation items available for
easy browsing and should look consistent.
This sets a max width on desktop to match the layout of the admin and
product page.

Include support link and consistent layout

---

source/stylesheets/screen.css.scss

We sometimes have "Admin" as a menu item, and when you are on the admin,
it says "Sign in".  This uses up a different amount of space, so set a
min width to ensure the navigation doesn't mover around when you browse
between the apps.

Make primary navigation consistent with other apps

---

README.md

The GDS way is to use OGL for documentation and MIT for codebases.

Add Licence (OGL)

---

source/javascripts/application.js

**WHAT:** 
This removes the current installation of Google Tag Manager in the tech docs. 
**WHY:**
This was done in preparation for the current installation of Google Analytics in the tech docs to be reconfigured.

Remove Tag Manager Implementation

---

source/documentation/requirements.md

There are certain steps that aren't actually required to get set up on GovWifi.
To avoid the misconception of needing to potentially do lots of work, make it clear
what is required to use GovWifi, and what should be followed to provide good QoS.
use of Static IP addresses has also been reworded, to explain the static IP address
is only required for the RADIUS servers.
Note that the requirement to allow VPN services has been left in as a requirement,
as their use is ubiquitous around most departments, and so should continue to function

restructure admin requirements to split out recommendations

---

source/documentation/manage.md
source/documentation/set_up.md
source/documentation/troubleshooting.md

Replaced all mentions of `support@` with a "contact us" link that goes to the support page.

Remove direct mentions of support@ email address

---

nginx.conf

Currently we serve the docs from both:
docs.wifi.service.gov.uk
www.docs.wifi.service.gov.uk
Make www requests are being 301 redirected

Redirect all requests to docs.wifi.service.gov.uk

---

config/tech-docs.yml

**IN THIS PR:**
- Add "Connect to GovWifi" link and "Offer GovWifi" link to the top navigation headers.
**BEFORE:**
------------------------------------------------------------------------------------------------------
**AFTER:**
------------------------------------------------------------------------------------------------------
**Any feedback/suggestions would be appreciated.**

Update tech docs headers

---

source/troubleshooting.html.md.erb

We need to make clear this content is for network administrators and not end-users in search engine results, as it currently ranks high for 'support' queries

Update troubleshooting to be clearer for administrators

---

source/documentation/set_up.md

We have improved the set up documentation to support prospective organisations understand and complete all the necessary steps for installing GovWifi in their organisation

Update set up instructions on tech docs

---

ci/pipelines/build-and-deploy.yml

A change to cf-resource overrides path specified in manifest.yml with the path specified in the pipeline. The directory manifest.yml is copied into has been changed to reflect this. Local cf cli
commands will still work.

Copy only build artefacts and manifest to deploy step

---

config/tech-docs.yml

This adds a footer link to the accessibility statement published as part of this PR: https://github.com/alphagov/govwifi-product-page/pull/218.
This is made possible by the newly exposed `footer_links` option in the `tech-docs-gem`.

fix: expose the accessibility statement

---

source/documentation/set_up.md

We don’t link to it from the setup page any more, so we need to link directly to the image.
Depends on:

Link directly to poster image

---

Dockerfile
docker-compose.yml

Because life is too short to wait for a full rebuild.

Enable LiveReload when running on Docker

---

config/tech-docs.yml

This is temporary and will be enabled back once we are ready to roll out changes to cookie opt-in model in the near future.

Disable GA

---

ci/pipelines/build-and-deploy.yml

This ensures self-update job finishes before deploy job starts, because there could be updates to the pipeline itself which won't get picked up in case the `deploy` job starts before the `self-update` job finishes.
For context, this was first fixed for product pages here: https://github.com/alphagov/govwifi-product-page/pull/253

Remove race condition in concourse pipeline

---

config/tech-docs.yml
source/accessibility.html.md.erb

The deadline for publishing an accessibility statement is 23 September 2020. The GovWifi technical documentation does not have a dedicated statement published although there is one for the website. 
Add an accessibility statement for tech docs with information from the August 2020 accessibility audit. Include a link in the bottom navigation to the accessibility statements for the GovWifi website and tech docs. Please note there is a separate statement on the tech doc template itself, which is being handled as part of a separate project.

Update accessibility statements

---

source/documentation/set_up.md

Organisations should connect to a radius server in each region
so they still have connectivity if an AWS region goes down.

Edit Radius Connection Guidance

---

source/certificate-rotation.html.md.erb
source/documentation/certificate-rotation.md
source/index.html.md.erb
source/manage.html.md.erb
source/requirements.html.md.erb
source/set_up.html.md.erb
source/troubleshooting.html.md.erb

This PR is to:
- add content to tell admins about the annual certificate rotation
- change the order that the sections display in the contents bar, and make it easier to add new sections in future (this is the 'weight' changes)
So that they: 
- know what to do, and can download the new certificates this year
- read this when they first set up GovWifi and know to expect it every year

Certificate rotation

---

source/documentation/manage.md

Added content that tells organisations to have a plan in case GovWifi is offline for a long time. 
So there's minimal disruption to end users if there's a severe incident. 
Trello card: https://trello.com/c/fJRlKLBB/1480-add-bcp-requirement-to-tech-docs

Add content about business continuity planning

---

source/accessibility.html.md.erb

Remove "we plan to fix" text left in accessibility statement
This was missed in previous change. As we are not responsible for the template, we should not make a statement on when we plan to fix.

Remove "we plan to fix" text left in accessibility statement

---

package-lock.json
package.json

Bump `govwifi-shared-frontend` to the latest release version.
A new version of the repo was released today, this will ensure we're using the newest version.
I've run the app locally and can't find any breaking changes.

Bump `govwifi-shared-frontend`

---

package-lock.json

Update version of govwifi-shared-frontend referenced
Using an earlier version (0.6.7) seems to be causing a error when we attempt to
deploy this with Concourse.

Update govwifi-shared-frontend package SHA

---

source/documentation/certificate-rotation.md

A name of the Intermediate cert needs to match the name stored in the 2022 subfolder.
Users are unable to download the Intermediate cert right now.

Update name of the Intermediate cert

---

Dockerfile

Change the package name from nodejs-npm to npm
The above package name has changed in the alpine image
Link to Trello card (if applicable): n/a

Replace the nodejs-npm with npm - package name has changed in alpine

---

README.md

Add the npm invocation required to successfully build the docs.
Because the docs won't build without it.

Add npm invocation to build instructions

---

source/documentation/set_up.md

H2 removed from Connect to GovWifi for individual use section. This is to prevent 'Connect for individual use' appearing in the navigation within 'setup GovWifi for your organisation'.
With the content changes now actioned 'Connect for individual use' is appearing as a navigation item from the H2. This change removes the H2 and means 'Connect for invididual use' doesn't appear in the navigation.
Connect to GovWifi for individual use shouldn't be a navigation item within 'Setup GovWifi for your organisation'. That could be confusing. The intention of the content changes is only to alert individual users landing on this section that they are in the wrong place.

Remove H2 from connect for individual use section

---

.github/workflows/deploy.yml

This PR will introduce a Github action to build and deploy our Tech Docs to PaaS, Govwifi space.
We are migrating this task away from our hosted in AWS Concourse to save taxpayer funds.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-434
The workflow can be re-run in Github. It will build and deploy to PaaS Govwifi sandbox. This would need to be removed using cf delete [application] when testing is complete.

Create build and deploy actions

---

Dockerfile
package-lock.json

Describe the change
Fix console javascript errors when App is created via 'make serve'
Describe why the change was necessary
Fix Errors.
Link to Trello card (if applicable): 
https://technologyprogramme.atlassian.net/browse/GW-471

GW-471 Remove --unsafe-perm from npm call

---

source/documentation/troubleshooting.md

Search the logs for admins was using an outdated (broken) link. Now updated to correct location.
Broken link in tech docs.
https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-608

Update link for search the logs

---

source/documentation/set_up.md

Text changes to make 'prioritise GovWifi profile' section of tech docs an optional step.
Prioritising the GovWifi profile depends on the organisation - it's not a mandatory step for all admins.
https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-790

Text changes for prioritise GovWifi profile

---

source/assets/govwifi-profile.xml

GovWifi service will use the new Root CA from May 2023, so this change needs to be reflected in a configuration file we have offer for the Windows machines.
There are two old Root CAs which also need to be removed as these are not in use sice 2019:
de 28 f4 a4 ff e5 b9 2f a3 c5 03 d1 a3 49 a7 f9 96 2a 82 12 - refers to the `GeoTrust Global CA`
32 3c 11 8e 1b f7 b8 b6 52 54 e2 e2 10 0d d6 02 90 37 f0 96 - refers to the `GeoTrust Primary Certification Authority`
To allow users to use Windows configuration file from May 2023 and beyond.
Link to Trello card (if applicable):

Remove legacy Root CAs and add new Root CA for the 2023 and beyond

---

source/documentation/certificate-rotation.md

Updated cert rotation copy: new links to certs, refs to 2022 updated to 2023.
Bring cert rotation 
https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-824

Update cert rotation tech doc for 2023

---

source/documentation/certificate-rotation.md

We want to ensure our Tech Doc guidance is in line with comms emailed to the users.
We need to ensure all docs are up to date before cert rotation.
Link to Trello card (if applicable):

Update a cert rotation guidance for Admins.

---

source/documentation/set_up.md

This text:
Configure your Network Access Server (access point) to make usernames private.
If allowed by your infrastructure vendor, set the Network Access Identifier (NAI) for your outer tunnel to be anonymous. See [RFC 7542](https://tools.ietf.org/html/rfc7542) for full details of permitted NAI syntax.
is removed from the documentation in this PR.
For accuracy, see more detail in GW-860.
[Jira ticket: ](https://technologyprogramme.atlassian.net/jira/software/projects/DDJTS/boards/251?assignee=628b458a40b157006f721ef5&selectedIssue=GW-860)

Remove network access server points text from documentation

---

config.rb

Remove Middleman setting
So menu will work correctly in github pages

Remove Middleman setting

---

.github/pull_request_template.md
README.md
config.rb
source/documentation/certificate-rotation.md
source/documentation/manage.md
source/documentation/requirements.md
source/documentation/set_up.md
source/documentation/troubleshooting.md

Update broken links due to migration
So that the pages can be found.
Link to Jira card (if applicable): 
[GW-1266](https://technologyprogramme.atlassian.net/browse/GW-1266)
[GW-1266]: https://technologyprogramme.atlassian.net/browse/GW-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Gw 1266 fix broken links

---

source/documentation/certificate-rotation.md

Certificate date is using 2023 date.
We have the new date for 2024 agreed already.

A change to reflect a certificate rotation date for 2024.

---

.github/ISSUE_TEMPLATE/default-issue-template.md

Using a default template, try and direct people to the correct support channel, as this isn't monitored for support.

Update issue templates

---

.github/workflows/build-tech-docs.yml
.github/workflows/deploy-to-github-pages.yml

Update github actions, add action to check for building the project on raise of PR.
Security, reliability, some actions were being deprecated, and the build/check action will give confidence the dependabot wont break anything :)
[GW-1646](https://technologyprogramme.atlassian.net/browse/GW-1676)
[GW-1729](https://technologyprogramme.atlassian.net/browse/GW-1729)
[GW-1646]: https://technologyprogramme.atlassian.net/browse/GW-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GW-1729]: https://technologyprogramme.atlassian.net/browse/GW-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [GW-1729] [GW-1646] Update github actions.

---

.github/ISSUE_TEMPLATE/config.yaml

Add config file to prevent issues being raised without using a template.
So that support issues can be directed in the correct channel.

Add config file to prevent blank issues

---

package-lock.json
package.json

Update URL Of Shared Frontend Package
We are migrating all of these packages to a dedicated GovWifi github organisation. This is due to the GDS/DSIT split.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=5e45277d29e6d00c970616c6&selectedIssue=GW-1851

Update URL Of Shared Frontend Package

---

.gitignore
app.json

Remove Heroku reference
Keeping deprecated or irrelevant code in codebase is bad practice, causes mental overhead and can potentially cause security vulnerabilities. 
[GW-1876](https://technologyprogramme.atlassian.net/browse/GW-1876)

GW-1876: Strip out any mention of heroku

---

package-lock.json
package.json

Update the shared frontend library
To keep it up to date with dependabot changes.
Link to JIRA card (if applicable):
[GW-2294](https://technologyprogramme.atlassian.net/browse/GW-2294)

chore: [GW-2294] Update Shared Library

---

Gemfile
Gemfile.lock
Makefile
config.rb

Update middleman to 4.6.2.
Not an easy job since we depend upon govuk-tech-docs which pins middleman to 4.5.1
Also MM 4.6.2 breaks the RedCarpet markdown renderer, so needed to replace with Kramdown, thanks Jos!
Security vulnerability with Thor used in Middleman.
[GW-2389](https://technologyprogramme.atlassian.net/browse/GW-2389)

fix: [GW-2389] update middleman to 4.6.2
